version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-fiber_app
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      - PORT=3000
